'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Coins, Droplet, Sparkles } from 'lucide-react';
import { formatNumber } from '@/lib/utils';
import { useToastStore } from '@/lib/stores/useToastStore';
import { useFloatingNumberStore } from '@/lib/stores/useFloatingNumberStore';

interface ResourceCollectorProps {
  pendingGold: number;
  pendingElixir: number;
  onCollect: () => Promise<void>;
}

export function ResourceCollector({ pendingGold, pendingElixir, onCollect }: ResourceCollectorProps) {
  const [isCollecting, setIsCollecting] = useState(false);
  const [showAnimation, setShowAnimation] = useState(false);
  const { success } = useToastStore();
  const { showGold, showElixir } = useFloatingNumberStore();

  const hasPending = pendingGold > 0 || pendingElixir > 0;

  const handleCollect = async () => {
    setIsCollecting(true);
    setShowAnimation(true);

    try {
      await onCollect();

      // Show floating numbers at center of screen
      const centerX = window.innerWidth / 2;
      const centerY = window.innerHeight / 2;

      if (pendingGold > 0) {
        showGold(centerX - 50, centerY, pendingGold);
      }
      if (pendingElixir > 0) {
        showElixir(centerX + 50, centerY, pendingElixir);
      }

      // Show success toast
      const resources = [];
      if (pendingGold > 0) resources.push(`${formatNumber(pendingGold)} gold`);
      if (pendingElixir > 0) resources.push(`${formatNumber(pendingElixir)} elixir`);
      success('Resources Collected!', `You collected ${resources.join(' and ')}`);

      // Keep animation visible for a moment
      setTimeout(() => setShowAnimation(false), 1500);
    } catch (error) {
      console.error('Failed to collect resources:', error);
      setShowAnimation(false);
    } finally {
      setIsCollecting(false);
    }
  };

  if (!hasPending && !showAnimation) {
    return (
      <Card className="border-2 border-dashed border-gray-300">
        <CardContent className="py-6">
          <div className="text-center text-sm text-muted-foreground">
            <Sparkles className="mx-auto mb-2 h-8 w-8 text-gray-400" />
            <p>No resources to collect</p>
            <p className="text-xs">Resources are generated by your mines and collectors</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="relative overflow-hidden border-2 border-amber-500 bg-gradient-to-br from-amber-50 to-purple-50 dark:from-amber-950 dark:to-purple-950">
      <AnimatePresence>
        {showAnimation && (
          <motion.div
            className="absolute inset-0 z-10 flex items-center justify-center bg-black/20"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          >
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: [0, 1.2, 1], rotate: [0, 360] }}
              transition={{ duration: 0.6 }}
              className="rounded-full bg-white p-4 shadow-2xl"
            >
              <Sparkles className="h-12 w-12 text-yellow-500" />
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <CardContent className="py-6">
        <div className="space-y-4">
          <div className="text-center">
            <h3 className="mb-2 text-lg font-bold">Resources Ready!</h3>
            <p className="text-sm text-muted-foreground">Collect your generated resources</p>
          </div>

          <div className="grid grid-cols-2 gap-4">
            {pendingGold > 0 && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="flex items-center justify-center gap-2 rounded-lg bg-gold/20 p-3"
              >
                <Coins className="h-6 w-6 text-gold-dark" />
                <div>
                  <p className="text-xs text-muted-foreground">Gold</p>
                  <p className="text-lg font-bold text-gold-dark">+{formatNumber(pendingGold)}</p>
                </div>
              </motion.div>
            )}

            {pendingElixir > 0 && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 }}
                className="flex items-center justify-center gap-2 rounded-lg bg-elixir/20 p-3"
              >
                <Droplet className="h-6 w-6 text-elixir-dark" />
                <div>
                  <p className="text-xs text-muted-foreground">Elixir</p>
                  <p className="text-lg font-bold text-elixir-dark">+{formatNumber(pendingElixir)}</p>
                </div>
              </motion.div>
            )}
          </div>

          <Button
            onClick={handleCollect}
            disabled={isCollecting}
            variant="game"
            className="w-full"
            size="lg"
          >
            {isCollecting ? (
              <span className="flex items-center gap-2">
                <Sparkles className="h-4 w-4 animate-spin" />
                Collecting...
              </span>
            ) : (
              <span className="flex items-center gap-2">
                <Sparkles className="h-4 w-4" />
                Collect Resources
              </span>
            )}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
